FROM openjdk:11-jdk
EXPOSE 8089
ADD target/yassine-sae4-gestion-station-ski:latest-1.0.jar  yassine-sae4-gestion-station-ski:latest-1.0.jar
ENTRYPOINT ["java","-jar","yassine-sae4-gestion-station-ski:latest-1.0.jar"]
